---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments

env:
  node: true
  
extends: 
  - 'airbnb-base'
  - 'plugin:jest/recomended'


overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extension:
    -error
    -ignorePackeges
    -js: always
  no-underscore-dangle: [2, { "allow": ["__filename", '__dirname'] }]
